Redirect to default thread on thread deletion
Mintplex-Labs/anything-llm pull request #2808
Opened 2024-12-11 20:58 UTC by shatfield4

### Pull Request Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #2767 

### What is in this change?

- Fixes UI/UX issue where on thread deletion, user would still be presented with the page of the deleted thread and sending messages here would throw a 404 error since the thread no longer exists
- Fixed by redirecting user back to default thread on thread deletion

### Additional Information

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

2024-12-11 21:53 UTC, timothycarambat requested changes
This does not handle the case where the user does a `bulkDelete` and are on a selected threadID which is is going to be removed.

This does work when clicking the more dots and deleting one-by-one

2024-12-12 01:00 UTC, timothycarambat approved these changes

2024-12-12 01:00 UTC, merged

2024-12-12 17:17 UTC, andydev404 commented
The only issue that I see with the fix is that now the toast is not gonna work as expected due that you're immediately redirecting to another page.

2024-12-12 17:53 UTC, timothycarambat commented
That's acceptable since it would only be the case when you deleted the page you are on, which would then show all current threads indicating the one you were on was deleted without showing a message.

This also works because of how thread handling is done downstream on desktop