devcontainer v1
Mintplex-Labs/anything-llm pull request #297
Opened 2023-10-26 22:47 UTC by franzbischoff

This PR does the following:

- Added configuration for creating a devcontainer with the environment ready for starting server:dev and frontend:dev
- Changes the location of eslint config in order to be global. In fact, Eslint is mostly useful when employed with the IDE extension. The package lint script uses prettier, not eslint.
- Creates a prettier config file and ignore file, so both CLI and IDE extensions have the same formatting rules.
- Tailwind is now integrated into the IDE.

Adjustments:
- settings.json needs the eslint config, so VSCode doesn't complain about the old format.
- package-lock.json is removed in favor of yarn.lock. The project uses yarn, not npm.
- Some adjustments were made on all "package.json" files.
- Added SERVER_ADDRESS in server/.env.example to fix a bug when using WSL.

Final words:

These standardizations of code format don't require to use of the devcontainer. One can still run the server and frontend and configure the extensions by hand in the system environment. Nevertheless, the devcontainer is a safer and quicker way to start developing.

I've tested in several ways and it is working. But who knows... 🤞

2023-11-07 02:54 UTC, franzbischoff reviewed
reviewd

2023-12-28 23:57 UTC, timothycarambat commented on .devcontainer/README.md
> +
Do we still need to support this now that we removed all python code from the codebase?

2023-12-28 23:58 UTC, timothycarambat requested changes
Looks like this will work great, i think the docs need a touch up because obviously we made a ton of changes while this was underway - namely that the collector was changed from Python to NodeJS, which should be easier now to run alongside everything else hopefully.

2023-12-29 02:08 UTC, franzbischoff reviewed
done

2024-01-06 17:47 UTC, franzbischoff reviewed
reviewed

2024-01-08 22:47 UTC, timothycarambat approved these changes

2024-01-08 23:31 UTC, merged